interface data {
  id: number
  name: string
}

export interface IDetailsPageDetails {
  id?: number
  src?: string
  image?: string
  name?: string
  vehicle_name?: string
  director?: string
  producer?: string
  release_date?: string
  characters?: data[]
  planets?: data[]
  starships?: data[]
  vehicles?: data[]
  species?: data[]
  created?: string
  edited?: string
  opening_crawl?: string
  height?: string
  mass?: string
  hair_color?: string
  eye_color?: string
  birth_year?: string
  gender?: string
  homeworld?: data[]
  films?: data[]
  rotation_period?: string
  orbital_period?: string
  diameter?: string
  climate?: string
  gravity?: string
  terrain?: string
  surface_water?: string
  population?: string
  residents?: data[]
  classification?: string
  designation?: string
  average_height?: string
  skin_colors?: string
  hair_colors?: string
  eye_colors?: string
  average_lifespan?: string
  language?: string
  people?: data[]
  model?: string
  manufacturer?: string
  cost_in_credits?: string
  length?: string
  max_atmosphere_speed?: string
  max_atmosphering_speed?: string
  crew?: string
  passengers?: string
  cargo_capacity?: string
  consumables?: string
  vehicle_class?: string
  hyperdrive_rating?: string
  MGLT?: string
  starship_class?: string
  pilots?: data[]
}
